name: app_flutter
description: A new Flutter project.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.1
  cupertino_icons: ^1.0.2
  flutter_inset_box_shadow: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  test: ^1.24.3

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/

  fonts:
    - family: Mulish
      fonts:
        - asset: assets/fonts/Mulish/static/Mulish-Black.ttf
          weight: 900
        - asset: assets/fonts/Mulish/static/Mulish-BlackItalic.ttf
          weight: 900
          style: italic
        - asset: assets/fonts/Mulish/static/Mulish-Bold.ttf
          weight: 700
        - asset: assets/fonts/Mulish/static/Mulish-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/Mulish/static/Mulish-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Mulish/static/Mulish-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: assets/fonts/Mulish/static/Mulish-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Mulish/static/Mulish-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: assets/fonts/Mulish/static/Mulish-Italic.ttf
          style: italic
        - asset: assets/fonts/Mulish/static/Mulish-Light.ttf
          weight: 300
        - asset: assets/fonts/Mulish/static/Mulish-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/Mulish/static/Mulish-Medium.ttf
          weight: 500
        - asset: assets/fonts/Mulish/static/Mulish-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Mulish/static/Mulish-Regular.ttf
        - asset: assets/fonts/Mulish/static/Mulish-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Mulish/static/Mulish-SemiBoldItalic.ttf
          weight: 600
          style: italic